# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
# Powerlevel 40K theme by Nidrax

console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - template: " {{.Icon}} "
    foreground: "007"
    background: "012"
    foreground_templates:
    - '{{ if contains "ubuntu" .OS }}#ffffff{{ end }}'
    - '{{ if contains "endeavouros" .OS }}#ffffff{{ end }}'
    - '{{ if contains "darwin" .OS }}008{{ end }}'
    background_templates:
    - '{{ if contains "ubuntu" .OS }}#dd6726{{ end }}'
    - '{{ if contains "endeavouros" .OS }}#7f3fbf{{ end }}'
    - '{{ if contains "darwin" .OS }}015{{ end }}'
    type: os
    style: diamond
  - properties:
      home_icon: "~"
      style: agnoster_short
    template: " {{ if ne \"~\" .PWD }}\uf07c {{ else }}\uf015 {{ end }}{{ .Path }} "
    foreground: "0"
    powerline_symbol: 
    background: "4"
    type: path
    style: powerline
  - properties:
      branch_icon: "\uf126 "
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
      mapped_branches:
        bug/*: "🐛 "
        feature/*: "🚀 "
      source: cli
    template: " {{ .UpstreamIcon }}{{ .HEAD }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    foreground: "0"
    powerline_symbol: 
    background: "2"
    type: git
    style: powerline
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}3{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}1{{ end }}"
    - "{{ if gt .Ahead 0 }}6{{ end }}"
    - "{{ if gt .Behind 0 }}215{{ end }}"
version: 3
final_space: true
